Bump poetry to handle build error
This is in response to the following error:
```
ERROR: pip's dependency resolver does not currently take into account
all the packages that are installed. This behaviour is the source of the
following dependency conflicts.
poetry 1.2.2 requires platformdirs<3.0.0,>=2.5.2, but you have
platformdirs 4.0.0 which is incompatible.
```